### ISSUE TITLE
Correction in decentralising the web blog post

### ISSUE THREAD

**Issue by taravancil** [tom-james-watson/tomjwatson.com#1]
Hi Tom! I finally read your post about Beaker and Dat, and it's really great! I think these kinds of introductory heres-the-decentralized-web-in-my-words type of posts are super helpful. I wanted to suggest a small correction:

> However, the folks at Code For Science have been doing amazing work on the Beaker Browser, which makes the distributed web a user-friendly reality that you can use today.

Code for Science actually doesn't work on Beaker, Beaker is an independent project that isn't officially connected to CSS or Dat :)

**Comment by tom-james-watson** [comment]
Thanks - I've updated that sentence.

Yeah, I enjoyed doing the write up. There are loads of things I'm interested in exploring with dat, so I'm sure you'll see more of me on #beakerbrowser/#dat!
